version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: todo-app
    working_dir: /var/www
    volumes:
      - ./:/var/www
    environment:
      APP_ENV: dev
      APP_DEBUG: 1
    depends_on:
      - db
    networks:
      - todo_network
    ports:
      - "8080:80"

  db:
    image: mysql:latest
    container_name: todo-db
    ports:
      - '${FORWARD_MYSQL_PORT:-3312}:3306'
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_ROOT_PASSWORD:-root}'
      MYSQL_DATABASE: '${DB_DATABASE:-todo_test}'
      MYSQL_USER: '${DB_USERNAME:-todo_user}'
      MYSQL_PASSWORD: '${DB_PASSWORD:-todo_password}'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'no'
    volumes:
      - db_todo:/var/lib/mysql
    networks:
      - todo_network

volumes:
  db_todo:

networks:
  todo_network:
    driver: bridge
